runtime: python39
entrypoint: gunicorn -b :$PORT app:app

# Optional environment variables
env_variables:
  ENV: 'production'

# Instance class (Optional: Set the instance type)
instance_class: F2

# Automatic scaling (Optional: Set automatic scaling settings)
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 3

# Set the minimum number of instances (Optional)
min_instances: 1
